### ISSUE TITLE
Detect steps in NuGet-Packages

### ISSUE THREAD

**Issue by kevinboss** [SpecFlowOSS/SpecFlow.Rider#14]
We developed an extensive Framework that provides various generic steps for our tests.
We deploy that framework using NuGet. The Plugin warns me that there are unresolved steps when I use these steps from the package.

**Comment by Socolin** [comment]
Hello,

Thanks for reporting the problem, it should be fixed in the version 1.3.2. You can download this here https://github.com/SpecFlowOSS/resharper-specflow/releases/tag/v1.3.2 (It should be available on the marketplace soon)

**Comment by kevinboss** [comment]
Thank you very much.

It doesn't seem to work. If I open the Assembly-Project itself and implement a SpecFlow tests it detects the same tests just fine.
The projects are .NET 4.8 using the csproj format that was introduced with Core (if that makes any difference?).
Please tell me if you need any further information that may help you, I don't just want to dump code since it is a proprietary project.

**Comment by Socolin** [comment]
I'm going to need a bit more information.

What is the structure of the step definition file in the nuget ? When you decompile it with rider (or if you can access the source) I would need to know if the steps are nested into another class or things like that. I don't need any code or method name just the structure like

```
using ...

namespace {
  public class {
    [Given("pattern")]
    public void Method() {
   }
  }
}
```

The easiest way for me would  be a small repro project. 

Otherwise, you can also try to run the the plugin in debug, it should be easy:
- Clone this repository
- Open it in Rider
- Run it with gradle (either from Rider or from the console if you don't have the gradle plugin configured) `./gradlew :runIde` (stay on the project selection list)
- Attach the process `dotnet exec --runtimeconfig` (use Action "Attach to process"
- Add a breakpoint in https://github.com/SpecFlowOSS/resharper-specflow/blob/master/src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Caching/StepsDefinitions/AssemblyStepDefinitions/AssemblyStepDefinitionCache.cs (The `Build` method) 
- Open your project in the new rider window
- Try to find why the steps from your assembly are not detected

The csproj format should not be a problem.

**Comment by kevinboss** [comment]
```
using ...

namespace {
  [Binding]
  [Scope(Tag = "tag")]
  public class {
    [Given("pattern")]
    public void Method() {
   }
  }
}
```

The structure is as you can see above. The only difference compared to your example is the scope tag as far as I can tell.

I will have a look at the problem over the weekend if that isn't the issue.

**Comment by Socolin** [comment]
This should works, I think I'm going to need a repro project or that you debug the plugin to understand the problem

**Comment by nemesv** [comment]
It seems there is an error in the `AssemblyStepDefinitionCache` it only stores the steps from the last step definition class in the cache. 
So if you have multiple types with the `Binding` attribute only steps from the last one are detected correctly.

**Comment by Socolin** [comment]
Ho nice catch, it seems this was one line below what it should be :p

@kevinboss Can you test if the version 1.3.4 (when available) fix the issue ?

**Comment by Socolin** [comment]
@kevinboss I'm closing this issue. It should works now, if you still encounters a problem with this, please let us know.
