### ISSUE TITLE
Language is not recognized from app.config

### ISSUE THREAD

**Issue by jaspervhaastert** [SpecFlowOSS/SpecFlow.Rider#162]
The plugin does not recognize the feature file language when set in an `app.config` file.
Rider underlines the whole file in red with the error message `The file does not contain a feature`.
Running the test is not an issue, then the language is correctly recognized from the `app.config` file.

Sample `app.config` file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
    </configSections>
    <specFlow>
        <language feature="nl-NL" />
    </specFlow>
</configuration>
```

Sample feature file:
```gherkin
Functionaliteit: Calculator

Scenario: Add two numbers
    Gegeven the first number is 50
    En the second number is 70
    Als the two numbers are added
    Dan the result should be 120
```

**Comment by Socolin** [comment]
Hello,

The plugin support the version 3 of specflow. But I think it can work if you add a specflow.json file, see 
 https://docs.specflow.org/projects/specflow/en/latest/Installation/Configuration.html

Does this fix your problem ?

**Comment by Socolin** [comment]
I don't know when I'll have time to support this, I see 2 solutions if you want to get it to work now:

- Since you could replace the app.config with the specflow.json there would be no extra file.
- If you cannot add this file, I think as a workaround for now you can add it on your side and put it in .gitignore.

I think it could be a simple change at those 2 location 
https://github.com/SpecFlowOSS/SpecFlow.Rider/blob/master/src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Caching/SpecflowJsonSettings/SpecflowSettingsFilesCache.cs#L33
https://github.com/SpecFlowOSS/SpecFlow.Rider/blob/master/src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Caching/SpecflowJsonSettings/SpecflowSettingsFilesCache.cs#L49
