### ISSUE TITLE
Code completion for steps defined in a dependency/nuget

### ISSUE THREAD

**Issue by NicoSchuett** [SpecFlowOSS/SpecFlow.Rider#199]
Hey,

when writing a feature file and the step definition is located within the same project, the code completion works like a charm. However, we are using generic step definitions from an installed dependency/nuget. These steps are not displayed by the code completion.

Is there any way how to get this working? Does Rider generally support this?

Edit: [This bug](https://github.com/SpecFlowOSS/SpecFlow.Rider/issues/14) states that it should be working :-)

Cheers
Nico

**Comment by Constante-ou-Mort** [comment]
Facing the same problem with autocomplete and code analyse, suggestions etc. when step class has a lot of methods. Performance is pretty sad :(

**Comment by NicoSchuett** [comment]
Is there any update?

**Comment by Constante-ou-Mort** [comment]
Not yet, it looks like the project is not developing at all 😑

**Comment by Socolin** [comment]
> @NicoSchuett Not yet, it looks like the project is not developing at all 😑

I'm keeping the project up-to-date with Rider but I don't have the energy to work on new features right now. Tricentis seems to have abandoned SpecFlow (See SpecFlow repo) so nobody else is available to help me on this.

If you want to help one thing can be to provide a small repro project (It'll save me some time when I get to it)

I also have some big changes to do on the completion to make it more usable and I'll probably do both when I'm working again on it.

This feature should happen at some point but I don't know when, if you really want this right now, PR are welcome :), It's open source :) (if you are interested, contact me before, so I can give you hint on how to do it correctly)

**Comment by Socolin** [comment]
Hello,

I' m not able to reproduce the problem.

Can you test with the latest version ?
If it still does not work, please provide a small repro so I can find what is broken ? I added a small test project you may use this as base fore the repro. https://github.com/SpecFlowOSS/SpecFlow.Rider/tree/master/testProjects/AdditionalStepAssembly

**Comment by Socolin** [comment]
I forgot a details, the new version is only available on the 2023.3 EAP for now, you can download it from https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/6993640518

**Comment by Andreas-Huber** [comment]
I investigated a similar problem that ultimately is probably in our codebase.
But I think I could reproduce the mentioned issue and I attached an example.



[SpecFlowExampleTests.zip](https://github.com/SpecFlowOSS/SpecFlow.Rider/files/13476937/SpecFlowExampleTests.zip)

If the `SharedSteps` class does not have the Binding attribute, the plugin will not detect the steps.

![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/13376471/19f51390-8b84-453a-8050-846a64132a9e)

The tests run though.

![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/13376471/0e38b5af-1133-4f4a-a8b7-b9d6b2a1a904)

When the Binding attribute is added the tests run trough and the plugin detects the step.

However, if you now take the SharedSteps class and move it to the Spec Flow Example tests project, it is detected by the plugin, but the tests fail due to an `Ambiguous step definitions` error.
From that I conclude, that the Binding attribute should not be necessary for abstract classes - but that's more a guess than knowledge.

### Rider version
```
JetBrains Rider 2023.3 EAP 8
Build #RD-233.11799.49, built on November 20, 2023
Non-Bundled Plugins:
  com.settler.rider.specflow (1.20.0) (Installed form the link above)
```
Same behavior with Rider 2023.2.3 and the plugin version 1.18.0.

**Comment by Andreas-Huber** [comment]
I tested it again, and with 1.21.0 the described issue is gone. The step is detected correctly.

![image](https://github.com/SpecFlowOSS/SpecFlow.Rider/assets/13376471/f7d85b92-1889-43e3-a37b-8e029cba7501)
